[package]
name = "sky-shader"
version = "0.0.0"
publish = false

[lib]
crate-type = ["lib", "dylib"]

[dependencies]
shared = { path = "../../shaders/shared" }
spirv-std.path = "../../../crates/spirv-std"
