[package]
name = "mouse-shader"
version = "0.0.0"
publish = false

[lib]
crate-type = ["dylib"]

[dependencies]
shared = { path = "../../shaders/shared" }
spirv-std.path = "../../../crates/spirv-std"
