[package]
name = "compute-shader"
version = "0.0.0"
publish = false

[lib]
crate-type = ["dylib", "lib"]

[dependencies]
spirv-std.path = "../../../crates/spirv-std"

[target.'cfg(not(target_arch = "spirv"))'.dependencies]
rayon = "1.5"
